name: Build & Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  yunzai-bot-v2:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to HUAWEI SWR
        uses: docker/login-action@v2
        with:
          registry: swr.cn-south-1.myhuaweicloud.com
          username: ${{ secrets.HUAWEISWR_USERNAME }}
          password: ${{ secrets.HUAWEISWR_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: |
            linux/amd64
            linux/arm64/v8
          tags: |
            swr.cn-south-1.myhuaweicloud.com/sirly/yunzai-bot:v2
            sirly/yunzai-bot:v2

  yunzai-bot-v2plus:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: v2plus

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to HUAWEI SWR
        uses: docker/login-action@v2
        with:
          registry: swr.cn-south-1.myhuaweicloud.com
          username: ${{ secrets.HUAWEISWR_USERNAME }}
          password: ${{ secrets.HUAWEISWR_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: |
            linux/amd64
            linux/arm64/v8
          tags: |
            swr.cn-south-1.myhuaweicloud.com/sirly/yunzai-bot:v2plus
            sirly/yunzai-bot:v2plus

  yunzai-bot-v3:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to HUAWEI SWR
        uses: docker/login-action@v2
        with:
          registry: swr.cn-south-1.myhuaweicloud.com
          username: ${{ secrets.HUAWEISWR_USERNAME }}
          password: ${{ secrets.HUAWEISWR_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: |
            linux/amd64
            linux/arm64/v8
          tags: |
            swr.cn-south-1.myhuaweicloud.com/sirly/yunzai-bot:v3
            sirly/yunzai-bot:v3

  yunzai-bot-v3plus:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: v3plus

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to HUAWEI SWR
        uses: docker/login-action@v2
        with:
          registry: swr.cn-south-1.myhuaweicloud.com
          username: ${{ secrets.HUAWEISWR_USERNAME }}
          password: ${{ secrets.HUAWEISWR_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: |
            linux/amd64
            linux/arm64/v8
          tags: |
            swr.cn-south-1.myhuaweicloud.com/sirly/yunzai-bot:v3plus
            sirly/yunzai-bot:v3plus
            sirly/yunzai-bot:latest